/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as BooksSlugChapterSlugRouteImport } from './routes/books.$slug.$chapterSlug'
import { Route as AdminBooksBookIdRouteImport } from './routes/admin.books.$bookId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugChapterSlugRoute = BooksSlugChapterSlugRouteImport.update({
  id: '/$chapterSlug',
  path: '/$chapterSlug',
  getParentRoute: () => BooksSlugRoute,
} as any)
const AdminBooksBookIdRoute = AdminBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/books/$bookId': typeof AdminBooksBookIdRoute
  '/books/$slug/$chapterSlug': typeof BooksSlugChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/books/$bookId': typeof AdminBooksBookIdRoute
  '/books/$slug/$chapterSlug': typeof BooksSlugChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/books/$bookId': typeof AdminBooksBookIdRoute
  '/books/$slug/$chapterSlug': typeof BooksSlugChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/books/$slug'
    | '/admin/'
    | '/admin/books/$bookId'
    | '/books/$slug/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/books/$slug'
    | '/admin'
    | '/admin/books/$bookId'
    | '/books/$slug/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/books/$slug'
    | '/admin/'
    | '/admin/books/$bookId'
    | '/books/$slug/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  BooksSlugRoute: typeof BooksSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug/$chapterSlug': {
      id: '/books/$slug/$chapterSlug'
      path: '/$chapterSlug'
      fullPath: '/books/$slug/$chapterSlug'
      preLoaderRoute: typeof BooksSlugChapterSlugRouteImport
      parentRoute: typeof BooksSlugRoute
    }
    '/admin/books/$bookId': {
      id: '/admin/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/admin/books/$bookId'
      preLoaderRoute: typeof AdminBooksBookIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBooksBookIdRoute: typeof AdminBooksBookIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBooksBookIdRoute: AdminBooksBookIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BooksSlugRouteChildren {
  BooksSlugChapterSlugRoute: typeof BooksSlugChapterSlugRoute
}

const BooksSlugRouteChildren: BooksSlugRouteChildren = {
  BooksSlugChapterSlugRoute: BooksSlugChapterSlugRoute,
}

const BooksSlugRouteWithChildren = BooksSlugRoute._addFileChildren(
  BooksSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  BooksSlugRoute: BooksSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
